stages:
  data_ingestion:
    cmd: python39 src/segmentation/pipeline/stage01_data_ingestion.py
    deps:
      - src/segmentation/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data

  prepare_base_model:
    cmd: python39 src/segmentation/pipeline/stage02_prepare_base_model.py
    deps:
      - src/segmentation/pipeline/stage02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python39 src/segmentation/pipeline/stage03_training.py
    deps:
      - src/segmentation/pipeline/stage03_training.py
      - src/segmentation/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - V_SPLIT
    outs:
      - artifacts/training/model

  evaluation:
    cmd: python39 src/segmentation/pipeline/stage04_evaluation.py
    deps:
      - src/segmentation/pipeline/stage04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/model
      - src/segmentation/utils/common.py
    metrics:
      - artifacts/evaluation/score.json:
          cache: false