artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: github zip file link # https://github.com/Falgit1/filename.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath : artifacts/prepare_callbacks/checkpoints_dir/model

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model

evaluation:
  root_dir: artifacts/evaluation
  score_file: artifacts/evaluation/score.json

